modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/anthonymendez/Toeknee-s-Simple-Tools"
license = "MIT"

[[mods]]
modId = "toeknees_simple_tools"
version = "${version}"
displayName = "Toeknee's Simple Tools"
authors = "Anthony Mendez"
description = '''
Mod that adds some simple tools to the game.
'''

[[dependencies.toeknees_simple_tools]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toeknees_simple_tools]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.toeknees_simple_tools]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "toeknees_simple_tools.mixins.json"
